# ---------- STAGE 1: Build ----------
FROM node:20 AS builder

WORKDIR /app


COPY . .
RUN npm install
RUN npm run build



# ---------- STAGE 2: Serve ----------
FROM nginx:stable-alpine

# Copie du build vers nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copie d'un nginx.conf optionnel
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]